export const commands = {
  economy: {
    name: '`ᗴᑕOᑎOᗰY`',
    desc: 'Comandos de *Economía* para ganar dinero y divertirte con tus amigos.',
    cmds: [
      { name: "work", alias: ["w", "work", "chambear", "trabajar"], uso: "", desc: "Ganar coins trabajando." },
      { name: "balance", alias: ["balance", "bal", "coins", "bank"], uso: "_<mention>_", desc: "Ver cuántos coins tienes." },
      { name: "deposit", alias: ["dep", "deposit", "d", "depositar"], uso: "_<amount|all>_", desc: "Depositar tus coins en el banco." },
      { name: "withdraw", alias: ["withdraw", "with", "retirar"], uso: "_<amount|all>_", desc: "Retirar tus coins del banco." },
      { name: "shop", alias: ["shop", "tienda", "buy", "comprar", "inventory", "inv", "inventario"], uso: "_<page>_", desc: "Ver la tienda del bot." },
      { name: "heal", alias: ["heal", "curar", "pocion", "potion"], uso: "", desc: "Curar salud para salir de aventuras." },
      { name: "invoke", alias: ["ritual", "invoke", "invocar"], uso: "", desc: "Hacer ritos de invocación." },
      { name: "einfo", alias: ["infoeconomy", "cooldowns", "economyinfo", "einfo"], uso: "", desc: "Ver tu información de economía y cooldowns." },
      { name: "coinflip", alias: ["cf", "flip", "coinflip"], uso: "_<amount / face|cross>_", desc: "Apostar coins en un cara o cruz." },
      { name: "casino", alias: ["apostar", "casino"], uso: "_<amount>_", desc: "Apostar coins en el casino." },
      { name: "slot", alias: ["slot"], uso: "_<amount>_", desc: "Apostar coins en el casino." },
      { name: "roulette", alias: ["rt", "roulette", "ruleta"], uso: "_<amount / red|black|green>_",  desc: "Apostar coins en una ruleta." },
      { name: "ppt", alias: ["ppt", "pvp"], uso: "_<mention / stone|paper|scissors>_", desc: "Jugar piedra, papel o tijera con el bot o un usuario." },
      { name: "tictactoe", alias: ["tictactoe", "ttc", "ttt", "xo"], uso: "_<hall>_", desc: "Iniciar o unirte a una partida de TicTacToe." },
      { name: "delttt", alias: ["delttt", "delttc", "delxo"], uso: "", desc: "Abandonar tu partida de TicTacToe activa." },
      { name: "ahorcado", alias: ["ahorcado", "hangman"], uso: "", desc: "Iniciar un juego de ahorcado." },
      { name: "acertijo", alias: ["acertijo", "riddle", "adivinanza"], uso: "", desc: "Adivinar un acertijo y ganar coins." },
      { name: "movie", alias: ["movie", "peli", "advp", "pelicula"], uso: "", desc: "Adivinar una película en emojis y ganar coins." },
      { name: "trivia", alias: ["trivia"], uso: "", desc: "Responder una pregunta de trivia y ganar coins." },
      { name: "flag", alias: ["flag", "country"], uso: "", desc: "Adivina el país por sus emojis y gana coins." },
      { name: "math", alias: ["math", "mates"], uso: "_<difficulty>_", desc: "Iniciar un juego de matemáticas." },
      { name: "crime", alias: ["crime", "crimen"], uso: "", desc: "Ganar coins rápido." },
      { name: "slut", alias: ["slut", "prostituirse"], uso: "", desc: "Ganar coins con trabajos de riesgo." },
      { name: "steal", alias: ["robar", "steal", "rob"], uso: "_<mention>_", desc: "Intentar robar coins a un usuario." },
      { name: "givecoins", alias: ["givecoins", "pay", "coinsgive"], uso: "_<amount|all / mention>_", desc: "Dar coins a un usuario." },
      { name: "daily", alias: ["daily", "diario"], uso: "", desc: "Reclamar tu recompensa diaria." },
      { name: "weekly", alias: ["weekly", "semanal"], uso: "", desc: "Reclamar tu recompensa semanal." },
      { name: "monthly", alias: ["monthly", "mensual"], uso: "", desc: "Reclamar tu recompensa mensual." },
      { name: "coffer", alias: ["cofre", "coffer"], uso: "", desc: "Reclamar tu cofre diario." },
      { name: "economyboard", alias: ["economyboard", "eboard", "baltop"], uso: "_<page>_", desc: "Ver el ranking de usuarios con más coins." },
      { name: "adventure", alias: ["adventure", "aventura"], uso: "", desc: "Ir de aventuras para ganar coins." },
      { name: "hunt", alias: ["cazar", "hunt"], uso: "", desc: "Cazar animales para ganar coins." },
      { name: "fish", alias: ["pescar", "fish"], uso: "", desc: "Ganar coins pescando." },
      { name: "mine", alias: ["mine", "minar"], uso: "", desc: "Realizar trabajos de minería y ganar coins." },
      { name: "dungeon", alias: ["dungeon", "mazmorra"], uso: "", desc: "Explorar mazmorras para ganar coins." },
    ],
  },
  gacha: {
    name: '`ᘜᗩᑕᕼᗩ`',
    desc: 'Comandos de *Gacha* para reclamar e intercambiar personajes.',
    cmds: [
      { name: "rollwaifu", alias: ["rollwaifu", "rw", "roll"], uso: "", desc: "Waifu o husbando aleatorio." },
      { name: "claim", alias: ["claim", "c", "reclamar"], uso: "_<cite / waifu>_", desc: "Reclamar un personaje." },
      { name: "harem", alias: ["harem", "waifus", "claims"], uso: "_<mention>_", desc: "Ver tus personajes reclamados." },
      { name: "charimage", alias: ["charimage", "waifuimage", "cimage", "wimage"], uso: "_<waifu>_", desc: "Ver una imagen aleatoria de un personaje." },
      { name: "charinfo", alias: ["charinfo", "winfo", "waifuinfo"], uso: "_<waifu>_", desc: "Ver información de un personaje." },
      { name: "deletewaifu",  alias: ["delchar", "deletewaifu", "delwaifu"], uso: "_<waifu>_", desc: "Eliminar un personaje reclamado." },
      { name: "favboard", alias: ["favtop", "favoritetop", "favboard"], uso: "", desc: "Ver el top de personajes favoritos." },
      { name: "gachainfo", alias: ["gachainfo", "ginfo", "infogacha"], uso: "", desc: "Ver tu información de gacha." },
      { name: "giveallharem", alias: ["giveallharem"], uso: "_<mention>_", desc: "Regalar todos tus personajes a otro usuario." },
      { name: "givechar", alias: ["givechar", "givewaifu", "regalar"], uso: "_<waifu / mention>_", desc: "Regalar un personaje a otro usuario." },
      { name: "haremshop", alias: ["wshop", "haremshop", "tiendawaifus"], uso: "_<page>_", desc: "Ver los personajes en venta." },
      { name: "buychar", alias: ["buyc", "buycharacter", "buychar"], uso: "_<waifu>_", desc: "Comprar un personaje en venta." },
      { name: "sell", alias: ["sell", "vender"], uso: "_<value> <waifu>_", desc: "Poner un personaje a la venta." },
      { name: "removesale", alias: ["removesale", "removerventa"], uso: "_<waifu>_", desc: "Eliminar un personaje en venta." },
      { name: "trade", alias: ["trade", "intercambiar"], uso: "_<your character / character 2>_", desc: "Intercambiar un personaje con otro usuario." },
      { name: "robwaifu", alias: ["robwaifu", "robarwaifu"], uso: "_<mention>_", desc: "Robar un personaje a otro usuario." },
      { name: "vote", alias: ["vote", "votar"], uso: "_<waifu>_", desc: "Votar por un personaje para subir su valor." },
      { name: "waifusboard", alias: ["waifusboard", "waifustop", "topwaifus", "wtop"], uso: "_<page>_", desc: "Ver el top de personajes con mayor valor." },
      { name: "serieinfo", alias: ["serieinfo", "ainfo", "animeinfo"], uso: "_<name>_", desc: "Información de un anime." },
      { name: "serielist", alias: ["serielist", "slist", "animelist"], uso: "", desc: "Listar series del bot." },
      { name: "setfavourite", alias: ["setfav", "setfavourite"], uso: "_<waifu>_", desc: "Establecer tu claim favorito." },
      { name: "deletefav", alias: ["deletefav", "delfav"], uso: "_<waifu>_", desc: "Borrar tu claim favorito." },
      { name: "setclaimmsg", alias: ["setclaim", "setclaimmsg"], uso: "_<text>_", desc: "Modificar el mensaje al reclamar un personaje." },
      { name: "delclaimmsg", alias: ["delclaimmsg", "resetclaimmsg"], uso: "", desc: "Restablecer el mensaje al reclamar un personaje." },
    ],
  },
  downloads: {
    name: '`ᗪOᗯᑎᒪOᗩᗪ`',
    desc: 'Comandos de *Descargas* para bajar contenido de distintas plataformas.',
    cmds: [
      { name: "facebook", alias: ["fb", "facebook"], uso: "_<url>_", desc: "Descargar un video de Facebook." },
      { name: "mediafire", alias: ["mediafire", "mf"], uso: "_<url>_", desc: "Descargar un archivo de MediaFire." },
      { name: "gdrive", alias: ["drive", "gdrive"], uso: "_<url>_", desc: "Descargar un archivo de Google Drive." },
      { name: "ytmp3", alias: ["play", "mp3", "ytmp3", "ytaudio", "playaudio"], uso: "_<url|query>_", desc: "Descargar una canción de YouTube." },
      { name: "ytmp4", alias: ["play2", "mp4", "ytmp4", "ytvideo", "playvideo"], uso: "_<url|query>_", desc: "Descargar un vídeo de YouTube." },
      { name: "ytsearch", alias: ["ytsearch", "search", "yts"], uso: "_<query>_", desc: "Buscar videos de YouTube." },
      { name: "spotify", alias: ["spotify", "sp"], uso: "_<url|query>_", desc: "Descargar una canción de Spotify." },
      { name: "instagram", alias: ["instagram", "ig", "reel"], uso: "_<url>_", desc: "Descargar un reel de Instagram." },
      { name: "tiktok", alias: ["tiktok", "tt"], uso: "_<url|query>_", desc: "Descargar un video de TikTok." },
      { name: "twitter", alias: ["twitter", "x"], uso: "_<url>_", desc: "Descargar un video o imagen de Twitter/X." },
      { name: "pinterest", alias: ["pinterest", "pin"], uso: "_<url|query>_", desc: "Buscar y descargar imágenes de Pinterest." },
      { name: "imagen", alias: ["imagen", "img", "image"], uso: "_<query>_", desc: "Buscar y descargar imágenes de Google." },
      { name: "apk", alias: ["apk", "aptoide", "apkdl"], uso: "_<query>_", desc: "Buscar y descargar aplicaciones de Aptoide." },
    ],
  },
  profile: {
    name: '`ᑭᖇOᖴIᒪᗴ`',
    desc: 'Comandos de *Perfil* para personalizar tu cuenta.',
    cmds: [
      { name: "profile", alias: ["profile", "perfil"], uso: "_<mention>_", desc: "Ver tu perfil o el de un usuario." },
      { name: "afk", alias: ["afk"], uso: "_<reason>_", desc: "Activar el modo AFK para que el bot avise cuando te mencionen." },
      { name: "level", alias: ["level", "lvl"], uso: "_<mention>_", desc: "Ver tu nivel y experiencia actual." },
      { name: "leaderboard", alias: ["lboard", "lb", "leaderboard"], uso: "_<page>_", desc: "Top de usuarios con más experiencia." },
      { name: "setbirth", alias: ["setbirth"], uso: "_<day/month/year|month/day>_", desc: "Establecer tu fecha de cumpleaños." },
      { name: "delbirth", alias: ["delbirth"], uso: "", desc: "Borrar tu fecha de cumpleaños." },
      { name: "setgenre", alias: ["setgenre"], uso: "_<man|women>_", desc: "Establecer tu género." },
      { name: "delgenre", alias: ["delgenre"], uso: "", desc: "Eliminar tu género del perfil." },
      { name: "setdesc", alias: ["setdescription", "setdesc"], uso: "_<text>_", desc: "Establecer tu descripción de perfil." },
      { name: "deldesc", alias: ["deldescription", "deldesc"], uso: "", desc: "Eliminar tu descripción de perfil." },
      { name: "sethobby", alias: ["setpasatiempo", "sethobby"], uso: "", desc: "Establecer tu pasatiempo." },
      { name: "delhobby", alias: ["delpasatiempo", "removehobby"], uso: "", desc: "Eliminar tu pasatiempo del perfil." },
      { name: "marry", alias: ["marry", "casarse"], uso: "_<mention>_", desc: "Casarte con alguien." },
      { name: "divorce", alias: ["divorce"], uso: "", desc: "Divorciarte de tu pareja." },
      { name: "setfavourite", alias: ["setfav", "setfavourite"], uso: "_<waifu>_", desc: "Establecer tu claim favorito." },
      { name: "delfav", alias: ["deletefav", "delfav"], uso: "_<waifu>_", desc: "Borrar tu claim favorito." }
    ],
  },
  sockets: {
    name: '`ՏOᑕKᗴTՏ`',
    desc: 'Comandos de *Sockets* para configurar y gestionar el bot.',
    cmds: [
      { name: "botinfo", alias: ["infobot", "botinfo"], uso: "", desc: "Obtener información del bot." },
      { name: "join", alias: ["join", "unir"], uso: "_<link>_", desc: "Unir al bot a un grupo." },
      { name: "leave", alias: ["leave", "salir"], uso: "", desc: "Salir de un grupo." },
      { name: "self", alias: ["self"], uso: "_<on|off>_", desc: "Hacer privado o público tu bot." },
      { name: "setname", alias: ["setbotname", "setname"], uso: "_<short / long>_", desc: "Cambiar el nombre del bot." },
      { name: "setbanner", alias: ["setbanner", "setbotbanner"], uso: "", desc: "Cambiar el banner del menú." },
      { name: "setprefix", alias: ["setprefix", "setbotprefix"], uso: "_<value>_", desc: "Cambiar el prefijo del bot." },
      { name: "setcurrency",  alias: ["setbotcurrency", "setcurrency"], uso: "_<value>_", desc: "Cambiar la moneda del bot." },
      { name: "setowner", alias: ["setbotowner", "setowner"], uso: "_<mention|number>_", desc: "Cambiar el dueño del bot." },
      { name: "setchannel", alias: ["setchannel", "setbotchannel"], uso: "_<link>_", desc: "Cambiar el canal del bot." },
      { name: "setlink", alias: ["setlink", "setbotlink"], uso: "_<link>_", desc: "Cambiar el enlace del bot." },
      { name: "setpfp", alias: ["setimage", "setpfp"], uso: "", desc: "Cambiar la imagen de perfil del bot." },
      { name: "setstatus", alias: ["setstatus"], uso: "_<value>_", desc: "Cambiar el estado del bot." },
      { name: "setusername", alias: ["setusername"], uso: "_<value>_", desc: "Cambiar el nombre de usuario del bot." },
    ],
  },
  stickers: {
    name: '`ՏTIᑕKᗴᖇՏ`',
    desc: 'Comandos de *Stickers* para crear y gestionar paquetes.',
    cmds: [
      { name: "sticker", alias: ["sticker", "s"], uso: "_<cite / image|video>_", desc: "Convertir una imagen o video a sticker." },
      { name: "stickers", alias: ["stickerpack", "spack", "stickers"], uso: "_<query|url>_", desc: "Buscar y descargar packs de stickers." },
      { name: "toimg", alias: ["toimg", "toimage"], uso: "_<cite / sticker>_", desc: "Convertir un sticker a imagen o GIF." },
      { name: "brat", alias: ["brat"], uso: "_<text|mention>_", desc: "Crear un sticker estilo brat con texto." },
      { name: "bratv", alias: ["bratv"], uso: "_<text|mention>_", desc: "Crear un video-sticker estilo brat." },
      { name: "newpack", alias: ["newpack", "newstickerpack"], uso: "_<name pack>_", desc: "Crear un nuevo paquete de stickers." },
      { name: "getpack", alias: ["getpack", "pack", "stickerpack"], uso: "_<name pack>_", desc: "Descargar un paquete de stickers." },
      { name: "delpack", alias: ["delpack"], uso: "_<name pack>_", desc: "Eliminar un paquete de stickers." },
      { name: "packlist", alias: ["packlist", "stickerpacks"], uso: "", desc: "Listar tus paquetes de stickers." },
      { name: "addsticker", alias: ["addsticker", "stickeradd"], uso: "_<name pack>_", desc: "Agregar un sticker a un paquete." },
      { name: "delsticker", alias: ["stickerdel", "delsticker"], uso: "_<name pack>_", desc: "Eliminar un sticker de un paquete." },
      { name: "setmeta", alias: ["setstickermeta", "setmeta"], uso: "_<author|pack>_", desc: "Establecer el pack y autor por defecto para tus stickers." },
      { name: "delmeta", alias: ["delmeta", "delstickermeta"], uso: "", desc: "Restablecer el pack y autor por defecto para tus stickers." },
      { name: "setpackname", alias: ["setstickerpackname", "setpackname", "packname"], uso: "_<name pack / new name pack>_", desc: "Cambiar el nombre de un paquete de stickers." },
      { name: "setpackdesc", alias: ["setstickerpackdesc", "setpackdesc", "packdesc"], uso: "_<name pack / desc>_", desc: "Establecer la descripción de un paquete de stickers." },
      { name: "setpackprivate", alias: ["setpackprivate", "setpackpriv", "packprivate"], uso: "_<name pack>_", desc: "Establecer un paquete de stickers como privado." },
      { name: "setpackpublic", alias: ["setpackpublic", "setpackpub", "packpublic"], uso: "_<name pack>_", desc: "Establecer un paquete de stickers como público." },
    ],
  },
  utils: {
    name: '`ᑌTIᒪITIᗴՏ`',
    desc: 'Comandos de *Utilidades* para tareas generales.',
    cmds: [
      { name: "menu", alias: ["allmenu", "help", "menu", "ayuda"], uso: "_<category>_", desc: "Ver el menú de comandos." },
      { name: "status", alias: ["status", "estado"], uso: "", desc: "Ver el estado del bot." },
      { name: "ping", alias: ["ping", "p", "speed"], uso: "", desc: "Medir el tiempo de respuesta del bot." },
      { name: "chatgpt", alias: ["ia", "chatgpt"], uso: "_<query>_", desc: "Realizar peticiones a ChatGPT." },
      { name: "delete", alias: ["del", "delete"], uso: "_<cite / message>_", desc: "Eliminar un mensaje." },
      { name: "getpic", alias: ["pfp", "getpic"], uso: "_<mention>_", desc: "Ver la foto de perfil de un usuario." },
      { name: "tourl", alias: ["tourl"], uso: "_<cite / image|video>_", desc: "Convertir una imagen en un enlace." },
      { name: "say", alias: ["say", "decir"], uso: "_<text>_", desc: "Repetir un mensaje como el bot." },
      { name: "translate", alias: ["translate", "trad", "traducir"], uso: "_<language / text>_", desc: "Traducir texto al idioma especificado." },
      { name: "get", alias: ["get", "fetch"], uso: "_<url>_", desc: "Realizar solicitudes GET a páginas web." },
      { name: "hd", alias: ["hd", "enhance", "remini"], uso: "_<cite / image>_", desc: "Mejorar la calidad de una imagen." },
      { name: "inspect", alias: ["inspect", "inspeccionar"], uso: "_<url>_", desc: "Ver información de grupos y canales de WhatsApp." },
      { name: "read", alias: ["readviewonce", "read", "readvo"], uso: "_<cite / image|video>_", desc: "Convertir imagen/video de una vista a contenido." },
      { name: "screenshot", alias: ["ss", "screenshot", "web"], uso: "_<url>_", desc: "Capturar una página web." },
      { name: "fakereply", alias: ["fakereply", "fake", "fitnah"], uso: "_<mention / text>_", desc: "Envia un mensaje con una respuesta falsa de alguien." },
      { name: "testwelcome", alias: ["testwelcome", "testgoodbye"], uso: "", desc: "Probar el mensaje de bienvenida o despedida." },
    ],
  },
  group: {
    name: '`ᘜᖇOᑌᑭ`',
    desc: 'Comandos de *Grupo* para administrar y moderar.',
    cmds: [
      { name: "alerts", alias: ["alerts", "alertas"], uso: "_<on|off>_", desc: "Activar o desactivar las alertas del grupo." },
      { name: "antilinks", alias: ["antilink", "antilinks", "antienlaces"], uso: "_<on|off>_", desc: "Activar o desactivar el anti-enlaces." },
      { name: "antistatus", alias: ["antistatus", "antiestados"], uso: "_<on|off>_", desc: "Activar o desactivar el anti-estados." },
      { name: "bot", alias: ["bot"], uso: "_<on|off>_", desc: "Activar o desactivar el bot en el grupo." },
      { name: "economy", alias: ["economy", "economia"], uso: "_<on|off>_", desc: "Activar o desactivar los comandos de economía." },
      { name: "gacha", alias: ["gacha", "rpg"], uso: "_<on|off>_", desc: "Activar o desactivar los comandos de gacha." },
      { name: "nsfw", alias: ["nsfw"], uso: "_<on|off>_", desc: "Activar o desactivar los comandos NSFW." },
      { name: "adminonly", alias: ["adminonly", "onlyadmin"], uso: "_<on|off>_", desc: "Permitir que solo los admins puedan usar los comandos." },
      { name: "welcome", alias: ["welcome", "bienvenida"], uso: "_<on|off>_", desc: "Activar o desactivar la bienvenida." },
      { name: "goodbye", alias: ["goodbye", "despedida"], uso: "_<on|off>_", desc: "Activar o desactivar la despedida." },
      { name: "setwelcome", alias: ["setwelcome"], uso: "_<value>_", desc: "Establecer un mensaje de bienvenida personalizado." },
      { name: "setgoodbye", alias: ["setgoodbye"], uso: "_<value>_", desc: "Establecer un mensaje de despedida personalizado." },
      { name: "close", alias: ["close", "cerrar"], uso: "_<time>_", desc: "Cerrar el grupo para que solo los admins puedan enviar mensajes." },
      { name: "open", alias: ["open", "abrir"], uso: "_<time>_", desc: "Abrir el grupo para que todos puedan enviar mensajes." },
      { name: "groupinfo", alias: ["gp", "groupinfo"], uso: "", desc: "Ver la información del grupo." },
      { name: "setgpbanner", alias: ["setgpbanner"], uso: "_<cite / image>_", desc: "Cambiar la imagen del grupo." },
      { name: "setgpname", alias: ["setgpname"], uso: "_<value>_", desc: "Cambiar el nombre del grupo." },
      { name: "setgpdesc", alias: ["setgpdesc"], uso: "_<value>_", desc: "Cambiar la descripción del grupo." },
      { name: "setgpstatus", alias: ["setgpstatus"], uso: "_<text|cite> -bg <color> -tc <color> -font <sans|serif|script|hand|condensed|heavy>_", desc: "Publicar un estado en el grupo." },
      { name: "kick", alias: ["kick", "ban", "bang"], uso: "_<mention|función>_", desc: "Expulsar a un usuario del grupo." },
      { name: "promote", alias: ["promote", "promover"], uso: "_<mention>_", desc: "Ascender a un usuario a administrador." },
      { name: "demote", alias: ["demote", "degradar"], uso: "_<mention>_", desc: "Descender a un usuario de administrador." },
      { name: "warn", alias: ["warn"], uso: "_<mention / reason>_", desc: "Darle una advertencia a un miembro del grupo." },
      { name: "warns", alias: ["warns"], uso: "_<mention>_", desc: "Ver todas las advertencias de un miembro del grupo." },
      { name: "delwarn", alias: ["delwarn"], uso: "_<mention / number|all>_", desc: "Eliminar una advertencia de un miembro del grupo." },
      { name: "setwarnlimit", alias: ["setwarnlimit"], uso: "_<number>_", desc: "Establecer el límite de advertencias del grupo." },
      { name: "tag", alias: ["hidetag", "tag", "tagall", "todos"], uso: "_<text>_", desc: "Mencionar a todos los usuarios del grupo." },
      { name: "link", alias: ["link"], uso: "", desc: "Obtener el enlace del grupo." },
      { name: "revoke", alias: ["revoke", "restablecer"], uso: "", desc: "Restablecer el enlace del grupo." },
      { name: "msgcount", alias: ["count", "mensajes", "messages", "msgcount"], uso: "_<mention / days>_", desc: "Obtener el conteo de mensajes de un usuario." },
      { name: "topcount", alias: ["topcount", "topmensajes", "topmsgcount", "topmessages"], uso: "_<days>_", desc: "Ver el top de usuarios con más mensajes en el grupo." },
      { name: "topinactive", alias: ["topinactive", "topinactivos", "topinactiveusers"], uso: "_<days>_", desc: "Ver el top de usuarios más inactivos del grupo." },
    ],
  },
  nsfw: {
    name: '`ᑎՏᖴᗯ`',
    desc: 'Comandos *NSFW* solo disponibles en grupos con el modo adulto activado.',
    cmds: [
      { name: "xnxx", alias: ["xnxx"], uso: "_<query|url>_", desc: "Buscar y descargar videos de XNXX." },
      { name: "xvideos", alias: ["xvideos"], uso: "_<query|url>_", desc: "Buscar y descargar videos de XVideos." },
      { name: "gelbooru", alias: ["gelbooru", "gbooru"], uso: "_<tag>_", desc: "Buscar imágenes en Gelbooru." },
      { name: "rule34", alias: ["r34", "rule34", "rule"], uso: "_<tag>_", desc: "Buscar imágenes en Rule34." },
      { name: "anal", alias: ["anal", "violar"], uso: "_<mention>_", desc: "Hacer un anal." },
      { name: "blowjob", alias: ["blowjob", "mamada", "bj"], uso: "_<mention>_", desc: "Dar una mamada." },
      { name: "boobjob", alias: ["boobjob"], uso: "_<mention>_", desc: "Hacer una rusa." },
      { name: "bondage", alias: ["bondage"], uso: "_<mention>_", desc: "Atar sin escapatoria." },
      { name: "bukkake", alias: ["bukkake"], uso: "_<mention>_", desc: "Hacer un bukkake." },
      { name: "cum", alias: ["cum"], uso: "_<mention>_", desc: "Venirse en alguien." },
      { name: "cummouth", alias: ["cummouth"], uso: "_<mention>_", desc: "Acabar en la boca de alguien." },
      { name: "cumshot", alias: ["cumshot"], uso: "_<mention>_", desc: "Disparar semen." },
      { name: "creampie", alias: ["creampie"], uso: "_<mention>_", desc: "Dejar un creampie." },
      { name: "deepthroat", alias: ["deepthroat"], uso: "_<mention>_", desc: "Hacer una garganta profunda." },
      { name: "facesitting", alias: ["facesitting"], uso: "_<mention>_", desc: "Sentarse en la cara de alguien." },
      { name: "fap", alias: ["fap", "paja"], uso: "_<mention>_", desc: "Hacerse una paja." },
      { name: "fingering", alias: ["fingering"], uso: "_<mention>_", desc: "Meter los dedos." },
      { name: "footjob", alias: ["footjob"], uso: "_<mention>_", desc: "Hacer una paja con los pies." },
      { name: "fuck", alias: ["fuck", "coger"], uso: "_<mention>_", desc: "Follarte a alguien." },
      { name: "futanari", alias: ["futanari", "futa"], uso: "_<mention>_", desc: "Lo mejor de los dos mundos." },
      { name: "grabboobs", alias: ["grabboobs"], uso: "_<mention>_", desc: "Agarrar tetas." },
      { name: "grope", alias: ["grope"], uso: "_<mention>_", desc: "Manosear a alguien." },
      { name: "handjob", alias: ["handjob"], uso: "_<mention>_", desc: "Hacer una paja." },
      { name: "lickass", alias: ["lickass"], uso: "_<mention>_", desc: "Lamer un culo." },
      { name: "lickdick", alias: ["lickdick"], uso: "_<mention>_", desc: "Lamer un pene." },
      { name: "lickpussy", alias: ["lickpussy"], uso: "_<mention>_", desc: "Lamer un coño." },
      { name: "orgy", alias: ["orgy", "orgia"], uso: "_<mention>_", desc: "Organizar una orgía." },
      { name: "pegging", alias: ["pegging"], uso: "_<mention>_", desc: "Dar por detrás." },
      { name: "sixnine", alias: ["sixnine", "69"], uso: "_<mention>_", desc: "Hacer un 69 con alguien." },
      { name: "spank", alias: ["spank", "nalgada"], uso: "_<mention>_", desc: "Dar una nalgada." },
      { name: "squirt", alias: ["squirt", "squirting"], uso: "_<mention>_", desc: "Tener un squirt." },
      { name: "suckboobs", alias: ["suckboobs"], uso: "_<mention>_", desc: "Chupar tetas." },
      { name: "thighjob", alias: ["thighjob"], uso: "_<mention>_", desc: "Hacer una entre piernas." },
      { name: "undress", alias: ["undress", "encuerar"], uso: "_<mention>_", desc: "Desnudar a alguien." },
      { name: "yaoi", alias: ["yaoi"], uso: "_<mention>_", desc: "Momento muy intenso." },
      { name: "yuri", alias: ["yuri", "tijeras"], uso: "_<mention>_", desc: "Hacer tijeras." },
    ],
  },
  anime: {
    name: '`ᗩᑎIᗰᗴ`',
    desc: 'Comandos de *Anime* para reaccionar con tus amigos.',
    cmds: [
      { name: "ppcouple", alias: ["ppcp", "ppcouple"], uso: "", desc: "Generar imágenes para amistades o parejas." },
      { name: "angry", alias: ["angry", "enojado", "enojada"], uso: "_<mention>_", desc: "Estar enojado." },
      { name: "bath", alias: ["bath", "bañarse"], uso: "_<mention>_", desc: "Bañarse." },
      { name: "bite", alias: ["bite", "morder"], uso: "_<mention>_", desc: "Morder a alguien." },
      { name: "bleh", alias: ["bleh", "meh"], uso: "_<mention>_", desc: "Sacar la lengua." },
      { name: "blowkiss", alias: ["blowkiss", "besito"], uso: "_<mention>_", desc: "Mandar un besito." },
      { name: "blush", alias: ["blush", "sonrojarse"], uso: "_<mention>_", desc: "Sonrojarse." },
      { name: "bonk", alias: ["bonk", "golpe"], uso: "_<mention>_", desc: "Dar un golpe divertido." },
      { name: "bored", alias: ["bored", "aburrido", "aburrida"], uso: "_<mention>_", desc: "Estar aburrido." },
      { name: "bully", alias: ["bully", "molestar"], uso: "_<mention>_", desc: "Molestar a alguien." },
      { name: "call", alias: ["call", "llamar"], uso: "_<mention>_", desc: "Llamar a alguien." },
      { name: "clap", alias: ["clap", "aplaudir"], uso: "_<mention>_", desc: "Aplaudir." },
      { name: "coffee", alias: ["coffee", "cafe"], uso: "_<mention>_", desc: "Tomar café." },
      { name: "cold", alias: ["cold"], uso: "_<mention>_", desc: "Tener frío." },
      { name: "comfort", alias: ["comfort", "consolar"], uso: "_<mention>_", desc: "Consolar a alguien." },
      { name: "cook", alias: ["cook", "cocinar"], uso: "_<mention>_", desc: "Cocinar algo delicioso." },
      { name: "cringe", alias: ["cringe", "avergonzarse", "asco"], uso: "_<mention>_", desc: "Sentirse avergonzado o incómodo." },
      { name: "cry", alias: ["cry", "llorar"], uso: "_<mention>_", desc: "Llorar." },
      { name: "cuddle", alias: ["cuddle", "acurrucarse"], uso: "_<mention>_", desc: "Acurrucarse con alguien." },
      { name: "curious", alias: ["curious", "curioso", "curiosa"], uso: "_<mention>_", desc: "Mostrar curiosidad." },
      { name: "dance", alias: ["dance", "bailar"], uso: "_<mention>_", desc: "Bailar." },
      { name: "dramatic", alias: ["dramatic", "drama"], uso: "_<mention>_", desc: "Drama." },
      { name: "draw", alias: ["draw", "dibujar"], uso: "_<mention>_", desc: "Dibujar." },
      { name: "drunk", alias: ["drunk", "ebrio", "ebria"], uso: "_<mention>_", desc: "Estar borracho." },
      { name: "eat", alias: ["eat", "nom", "comer"], uso: "_<mention>_", desc: "Comer algo delicioso." },
      { name: "facepalm", alias: ["facepalm"], uso: "_<mention>_", desc: "Darte una palmada en la cara." },
      { name: "gaming", alias: ["gaming", "jugar"], uso: "_<mention>_", desc: "Jugar videojuegos." },
      { name: "greet", alias: ["greet", "hola"], uso: "_<mention>_", desc: "Saludar a alguien." },
      { name: "handhold", alias: ["handhold", "tomar"], uso: "_<mention>_", desc: "Tomar de la mano." },
      { name: "happy", alias: ["happy", "feliz"], uso: "_<mention>_", desc: "Saltar de felicidad." },
      { name: "heat", alias: ["heat", "calor"], uso: "_<mention>_", desc: "Tener calor." },
      { name: "highfive", alias: ["highfive", "chocar"], uso: "_<mention>_", desc: "Dar un choca esos cinco." },
      { name: "hug", alias: ["hug", "abrazar"], uso: "_<mention>_", desc: "Dar un abrazo." },
      { name: "impregnate", alias: ["impregnate", "embarazar", "preg", "preñar"], uso: "_<mention>_", desc: "Embarazar a alguien." },
      { name: "jump", alias: ["jump", "saltar"], uso: "_<mention>_", desc: "Saltar." },
      { name: "kill", alias: ["kill", "matar"], uso: "_<mention>_", desc: "Toma tu arma y mata a alguien." },
      { name: "kiss", alias: ["kiss", "muak"], uso: "_<mention>_", desc: "Dar un beso." },
      { name: "kisscheek", alias: ["kisscheek", "beso", "besar"], uso: "_<mention>_", desc: "Beso en la mejilla." },
      { name: "laugh", alias: ["laugh", "reír"], uso: "_<mention>_", desc: "Reírse de alguien." },
      { name: "lewd", alias: ["lewd"], uso: "_<mention>_", desc: "Hacer algo lascivo." },
      { name: "lick", alias: ["lick", "lamer"], uso: "_<mention>_", desc: "Lamer a alguien." },
      { name: "love", alias: ["love", "amor"], uso: "_<mention>_", desc: "Sentirse enamorado." },
      { name: "nope", alias: ["nope", "nop"], uso: "_<mention>_", desc: "Negarse a hacer algo." },
      { name: "pat", alias: ["pat", "acariciar"], uso: "_<mention>_", desc: "Acariciar a alguien." },
      { name: "peek", alias: ["peek"], uso: "_<mention>_", desc: "Espiar a alguien." },
      { name: "poke", alias: ["poke", "picar"], uso: "_<mention>_", desc: "Dar un golpecito a alguien." },
      { name: "pout", alias: ["pout", "mueca"], uso: "_<mention>_", desc: "Hacer pucheros." },
      { name: "psycho", alias: ["psycho", "loco", "loca"], uso: "_<mention>_", desc: "Tener un ataque de locura." },
      { name: "punch", alias: ["punch", "golpear"], uso: "_<mention>_", desc: "Dar un puñetazo." },
      { name: "push", alias: ["push", "empujar"], uso: "_<mention>_", desc: "Empujar a alguien." },
      { name: "run", alias: ["run", "correr"], uso: "_<mention>_", desc: "Correr." },
      { name: "sad", alias: ["sad", "triste"], uso: "_<mention>_", desc: "Expresar tristeza." },
      { name: "scared", alias: ["scared", "asustado", "asustada"], uso: "_<mention>_", desc: "Estar asustado." },
      { name: "scream", alias: ["scream", "gritar"], uso: "_<mention>_", desc: "Gritar." },
      { name: "seduce", alias: ["seduce", "seducir"], uso: "_<mention>_", desc: "Seducir a alguien." },
      { name: "shy", alias: ["shy", "timido", "timida"], uso: "_<mention>_", desc: "Sentir timidez." },
      { name: "sing", alias: ["sing", "cantar"], uso: "_<mention>_", desc: "Cantar." },
      { name: "slap", alias: ["slap", "bofetada"], uso: "_<mention>_", desc: "Dar una bofetada." },
      { name: "sleep", alias: ["sleep", "dormir"], uso: "_<mention>_", desc: "Tumbarse a dormir." },
      { name: "smile", alias: ["smile", "sonreir"], uso: "_<mention>_", desc: "Sonreír." },
      { name: "smoke", alias: ["smoke", "fumar"], uso: "_<mention>_", desc: "Fumar." },
      { name: "smug", alias: ["smug", "presumir"], uso: "_<mention>_", desc: "Actuar presumido." },
      { name: "sniff", alias: ["sniff", "oler"], uso: "_<mention>_", desc: "Oler a alguien." },
      { name: "snuggle", alias: ["snuggle", "acurrucar", "acurrucarse"], uso: "_<mention>_", desc: "Acurrucarse con alguien." },
      { name: "spit", alias: ["spit", "escupir"], uso: "_<mention>_", desc: "Escupir." },
      { name: "stare", alias: ["stare", "mirar"], uso: "_<mention>_", desc: "Mirar fijamente a alguien." },
      { name: "step", alias: ["step", "pisar"], uso: "_<mention>_", desc: "Pisar a alguien." },
      { name: "think", alias: ["think", "pensar"], uso: "_<mention>_", desc: "Pensar en algo." },
      { name: "thinkhard", alias: ["thinkhard"], uso: "_<mention>_", desc: "Pensar intensamente." },
      { name: "tickle", alias: ["tickle", "cosquillas"], uso: "_<mention>_", desc: "Hacer cosquillas." },
      { name: "trip", alias: ["trip", "tropezar"], uso: "_<mention>_", desc: "Tropezar con alguien." },
      { name: "walk", alias: ["walk", "caminar"], uso: "_<mention>_", desc: "Caminar." },
      { name: "wave", alias: ["wave", "saludar"], uso: "_<mention>_", desc: "Saludar con la mano." },
      { name: "wink", alias: ["wink", "guiñar"], uso: "_<mention>_", desc: "Guiñar un ojo." },
    ],
  },
}
